

stages:
- build
- deploy

# Job pour construire l'application (front et/ou back)
build_job:
  stage: build
  image: gcr.io/kaniko-project/executor:latest
  services:
  - docker:dind
  variables:
    CI_REGISTRY: "docker.io"
  script:
  - echo "Construction de l'application..."
  - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  - /kaniko/executor --context ./pli --dockerfile Dockerfile --destination crissime/pli-front:dev-${CI_COMMIT_SHORT_SHA}
  - /kaniko/executor --context ./signaling --dockerfile Dockerfile --destination crissime/pli-back:dev-${CI_COMMIT_SHORT_SHA}


deploy_to_dev:
  stage: deploy
  script:
  - echo "Déploiement sur l'environnement de développement..."
  - kubectl apply -f k8s-dev/front --namespace=dev
  - kubectl apply -f k8s-dev/back --namespace=dev
