stages:
- calculate_tag
- build_dev
- build_prod
- deploy_dev
- deploy_prod

workflow:
  rules:
  - if: $CI_COMMIT_MESSAGE =~ /\s*-k8s\s*/


deploy_to_prod:
  stage: deploy_prod
  image: bitnami/kubectl:latest
  script:
  - TAG=$(cat NEW_TAG)
  - cat $KUBECONFIG_DATA | base64 -d > kubeconfig
  - export KUBECONFIG=$CI_PROJECT_DIR/kubeconfig
  - echo "Mise à jour des images pour l'environnement de production..."
  - 'sed -i "s|image: crissime/pli-front:.*|image:crissime/pli-front:2.0.0|g" k8s-prod/front/deploy_front.yaml'
  - 'sed -i "s|image: crissime/pli-back:.*|image:crissime/pli-back:2.0.0|g" k8s-prod/backend/deploy_back.yaml'
  - kubectl apply -f k8s/front --namespace=prod
  - kubectl apply -f k8s/backend --namespace=prod
  tags:
    - k8s
  rules:
  - if: $CI_COMMIT_BRANCH == "main"