

stages:
- build
- deploy

# Job pour construire l'application (front et/ou back)
build_job:
  stage: build
  image: docker:latest
  services:
  - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
  - echo "Construction de l'application..."
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  - docker build --build-arg EACT_APP_BACKEND=https://pli-dev.ketsuna.com -t crissime/pli-front:dev-${CI_COMMIT_SHORT_SHA} ./pli
  - docker build --build-arg CORS_ORIGIN=https://pli-dev.ketsuna.com  -t crissime/pli-back:dev-${CI_COMMIT_SHORT_SHA} ./signaling
  - docker push crissime/pli-front:dev-${CI_COMMIT_SHORT_SHA}
  - docker push crissime/pli-back:dev-${CI_COMMIT_SHORT_SHA}


deploy_to_dev:
  stage: deploy
  script:
  - echo "Déploiement sur l'environnement de développement..."
  - kubectl apply -f k8s-dev/front --namespace=dev
  - kubectl apply -f k8s-dev/back --namespace=dev
