stages:
- build
- deploy

build_job:
  stage: build
  image: gcr.io/kaniko-project/executor:v1.23.2-debug
  variables:
    FF_USE_ADVANCED_POD_SPEC_CONFIGURATION: 1
  script:
  - echo "Construction de l'application..."
  - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  - /kaniko/executor --context ./pli --build-arg EACT_APP_BACKEND=https://pli-dev.ketsuna.com  --dockerfile Dockerfile --destination crissime/pli-front:dev-${CI_COMMIT_SHORT_SHA} 
  - /kaniko/executor --context ./signaling --build-arg CORS_ORIGIN=https://pli-dev.ketsuna.com  --dockerfile Dockerfile --destination crissime/pli-brack:dev-${CI_COMMIT_SHORT_SHA} 

deploy_to_dev:
  stage: deploy
  image: bitnami/kubectl:latest
  script:
  - cat $KUBECONFIG_DATA | base64 -d > kubeconfig
  - export KUBECONFIG=$CI_PROJECT_DIR/kubeconfig
  - echo "mise a jour des images"
  - 'sed -i "s|image: crissime/pli-front:.*|image: crissime/pli-front:dev-${CI_COMMIT_SHORT_SHA}|g" k8s-dev/front/deploy_front.yaml'
  - 'sed -i "s|image: crissime/pli-back:.*|image: crissime/pli-back:dev-${CI_COMMIT_SHORT_SHA}|g" k8s-dev/backend/deploy_backend.yaml'
  - echo "Déploiement sur l'environnement de développement..."
  - kubectl apply -f k8s-dev/front --namespace=dev
  - kubectl apply -f k8s-dev/backend --namespace=dev
