image: docker:20.10 # Image Docker globale pour tous les jobs nécessitant Docker

services:
- docker:20.10-dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

stages:
- build
- deploy

# Job pour construire l'application (front et/ou back)
build_job:
  stage: build
  script:
  - echo "Construction de l'application..."
  - docker build --build-arg EACT_APP_BACKEND=https://pli-dev.ketsuna.com -t crissime/pli-front:dev-${CI_COMMIT_SHORT_SHA} ./pli
  - docker build --build-arg CORS_ORIGIN=https://pli-dev.ketsuna.com  -t crissime/pli-back:dev-${CI_COMMIT_SHORT_SHA} ./signaling
  - docker push crissime/pli-front:dev-${CI_COMMIT_SHORT_SHA}
  - docker push crissime/pli-back:dev-${CI_COMMIT_SHORT_SHA}
  only:
  - /^test-k8s$/
  except:
  - master

deploy_to_dev:
  stage: deploy
  script:
  - echo "Déploiement sur l'environnement de développement..."
  - kubectl apply -f k8s-dev/front --namespace=dev
  - kubectl apply -f k8s-dev/back --namespace=dev
  only:
  - /^test-k8s$/
  except:
  - master

