stages:
- build
- deploy

deploy_to_dev:
  stage: deploy
  image: bitnami/kubectl:latest
  script:
  - cat /builds/module-9681/activity-52182/group-1038037.tmp/KUBECONFIG_DATA | base64 -d > kubeconfig
  - export KUBECONFIG=$CI_PROJECT_DIR/kubeconfig
  - echo "Déploiement sur l'environnement de développement..."
  - kubectl apply -f k8s-dev/front --namespace=dev
  - kubectl apply -f k8s-dev/back --namespace=dev
