stages:
- build
- deploy

deploy_to_dev:
  stage: deploy
  image: bitnami/kubectl:latest
  script:
  - ls -la
  - echo "$KUBECONFIG_DATA" > kubeconfig
  - ls -la
  - export KUBECONFIG=$CI_PROJECT_DIR/kubeconfig
  - echo "Déploiement sur l'environnement de développement..."
  - kubectl apply -f k8s-dev/front --namespace=dev
  - kubectl apply -f k8s-dev/back --namespace=dev
