services:
  
  nginx:
    build:
      context: ./pli
      dockerfile: Dockerfile
    ports:
    # server ports 80 and 443 for http and https
      - "80:80"
      - "443:443"
    volumes: 
    # mount the certs folder to the nginx container
      - ./certs:/etc/nginx/certs
    restart: always
    networks:
      - main
    #     ipv4_address: 192.168.1.10

  backend:
    build:
      context: ./signaling
      dockerfile: Dockerfile.dev
    ports:
    # server ports 8000 and 2000-2020 for webRTC
      - "8000:8000"
      - "2000-2020:2000-2020/udp"
    volumes:
      - ./signaling/src/app.ts:/app/src/app.ts
    environment:
      - CORS_ORIGIN=https://localhost:3000
    restart: always
    networks:
      - main
    #     ipv4_address: 192.168.1.20

# optional network configuration
networks:
  main:
    driver: bridge
    # ipam:
    #   config:
    #     - subnet: 192.168.1.0/24