services:
  nginx:
    build:
      context: ./pli
      dockerfile: Dockerfile
    ports:
    # server ports 80 and 443 for http and https
      - "80:80"
      - "443:443"
    volumes:
    # mount the certs folder to the nginx container
      - ./certs:/etc/nginx/certs
    restart: always
    networks:
      - main
    #     ipv4_address: 192.168.1.10
  backend:
    build:
      context: ./signaling
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - CORS_ORIGIN=https://localhost
      - DATABASE_URL=file:./dev.db
    restart: always
    networks:
      - main

  whisper:
    build:
      context: ./whisper
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - CORS_ORIGIN=https://localhost
      - WHISPER_HOST=0.0.0.0
      - WHISPER_PORT=5000
      - MODEL_SIZE=small
      - DEVICE=cpu
      - COMPUTE_type=int8
    restart: always
    networks:
      - main

networks:
  main:
    driver: bridge
