services:
  
  nginx:
    build:
      context: ./pli
      dockerfile: Dockerfile
    ports:
    # server ports 80 and 443 for http and https
      - "80:80"
      - "443:443"
    volumes: 
    # mount the certs folder to the nginx container
      - ./certs:/etc/nginx/certs
    environment:
      - REACT_APP_BACKEND=${REACT_APP_BACKEND}
    restart: always
    networks:
      - main

  backend:
    build:
      context: ./signaling
      dockerfile: Dockerfile
    ports:
    # server ports 8000 and 2000-2020 for webRTC
      - "8000:8000"
      - "2000-2020:2000-2020/udp"
    volumes:
      - ./signaling/src/app.ts:/app/src/app.ts
      - ./certs:/app/certs
    environment:
      - CERTS_PATH=${CERTS_PATH}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - WEBRTC_LISTEN_IP=${WEBRTC_LISTEN_IP}
      - WEBRTC_ANNOUNCED_ADDRESS=${WEBRTC_ANNOUNCED_ADDRESS}
    restart: always
    networks:
      - main

# optional network configuration
networks:
  main:
    driver: bridge