apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-dev
spec:
  selector:
    matchLabels:
      app: backend-dev
  template:
    metadata:
      labels:
        app: backend-dev
    spec:
      volumes:
      - name: cert
        secret:
          secretName: mysecret-dev
      containers:
      - name: backend-dev
        image: ghcr.io/exatombe/pli-back:latest
        resources:
          limits:
            memory: "250Mi"
            cpu: "250m"
        ports:
        - containerPort: 8000
        env:
        - name: CORS_ORIGIN
          value: https://pli.ketsuna.com
        - name: DATABASE_URL
          value: "file:./dev.db"
        volumeMounts:
        - name: cert
          mountPath: "/app/certs"
