apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisper
spec:
  selector:
    matchLabels:
      app: whisper
  template:
    metadata:
      labels:
        app: whisper
    spec:
      containers:
      - name: whisper
        image: crissime/pli-whisper:latest
        env:
        - name: CORS_ORIGIN
          value: "https://pli-dev.ketsuna.com"
        - name: WHISPER_HOST
          value: "0.0.0.0"
        - name: WHISPER_PORT
          value: "5000"
        - name: MODEL_SIZE
          value: small
        - name: DEVICE
          value: cuda
        - name: COMPUTE_TYPE
          value: float32
        resources:
          limits:
            memory: "2Gi"
            cpu: "1"
            nvidia.com/gpu: "1"
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: /models
          name: model-storage
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: model-pvc
