apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-pvc
spec:
  accessModes:
  - ReadWriteMany # Assurez-vous que l'accessMode est compatible avec votre PV
  resources:
    requests:
      storage: 10Gi
