apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-dev
spec:
  selector:
    matchLabels:
      app: front-dev
  template:
    metadata:
      labels:
        app: front-dev
    spec:
      volumes:
      - name: cert
        secret:
          secretName: mysecret-dev
      - name: conf
        configMap:
          name: conf-nginx-dev
      containers:
      - name: front-dev
        image: crissime/pli-front:latest
        resources:
          limits:
            memory: "250Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: cert
          mountPath: "/etc/nginx/certs/"
        - name: conf
          mountPath: "/etc/nginx/conf.d/"
        env:
        - name: "REACT_APP_BACKEND"
          value: "https://pli.ketsuna.com"
