apiVersion: v1
kind: Service
metadata:
  name: front-svc-dev
spec:
  type: NodePort
  selector:
    app: front-dev
  ports:
  - port: 443
    name: "https"
    targetPort: 443
    nodePort: 30142
  - port: 80
    name: "http"
    targetPort: 80

