apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-libretranslate
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: /data
