apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-libretranslate
spec:
  storageClassName: local-storage
  resources:
    requests:
      storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
