FROM node:18

WORKDIR /app

COPY package*.json ./
COPY tsconfig.json ./

RUN npm install

COPY . .

# RUN npx tsc

EXPOSE 8000
EXPOSE 2000-2020/udp

# CMD ["node", "dist/app.js"]

CMD ["npm", "run", "start"]
