apiVersion: v1
kind: Service
metadata:
  name: front-svc
spec:
  type: NodePort
  selector:
    app: front
  ports:
  - port: 443
    name: "https"
    targetPort: 443
    nodePort: 30141
  - port: 80
    name: "http"
    targetPort: 80

